Repository sheinsight/shineout-next, pull requests merged in 2024-11, with the labels that each got.

#778 fix: 修复 `Select` 禁用模式下 icon 样式异常、`DatePicker` 禁用后可聚焦的问题
  package.json
  packages/base/src/date-picker/date-picker.tsx
  packages/shineout-style/src/select/select.ts
  packages/shineout/src/date-picker/__doc__/changelog.cn.md
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug

#783 fix: 修复 `Select` 在 value 为空对象时 placeholder 失效的问题
  package.json
  packages/base/src/select/result.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug

#800 fix: 修复 `Cascader` 在开启 `unmatch` 情况下指定 renderItem 为 string 类型时渲染异常的问题
  package.json
  packages/base/src/select/result.tsx
  packages/base/src/select/result.type.ts
  packages/base/src/select/select.tsx
  packages/hooks/src/components/use-tree/use-tree.ts
  packages/hooks/src/components/use-tree/use-tree.type.ts
  packages/shineout/src/cascader/__doc__/changelog.cn.md
Labels: bug

#807 fix: 修复 `Select` 开启创建选项后无法选中创建内容的问题
  package.json
  packages/base/src/select/select.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug

#808 fix: 修复 `Form.FieldSet` 设置默认值覆盖前者初始化值的问题
  packages/base/src/form/form.tsx
  packages/hooks/src/components/use-form/use-form-control/use-form-control.ts
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/card/__test__/__snapshots__/card.spec.tsx.snap
  packages/shineout/src/form/__example__/001-base.tsx
  packages/shineout/src/form/__example__/test-001-base-form.tsx
  packages/shineout/src/input/__test__/__snapshots__/input.spec.tsx.snap
Labels: bug, playground

#810 fix: 修复 `Select` 默认事件引起的点击异常问题(Regression: since v3.4.4)
  package.json
  packages/base/src/select/select.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug

#814 fix: 修复 `Badge` 间距 css var 丢失的问题
  package.json
  packages/shineout/src/badge/__doc__/changelog.cn.md
  packages/theme/src/badge/badge.ts
  packages/theme/src/badge/token.ts
  packages/theme/src/badge/type.ts
Labels: bug, playground

#819 fix: 修复 `Select` 开启 `filterSameChange` 后单选模式下选择重复项无法关闭面板的问题
  package.json
  packages/base/src/select/select.tsx
  packages/hooks/src/common/use-input-able/use-Input-able.ts
  packages/hooks/src/common/use-input-able/use-Input-able.type.ts
  packages/hooks/src/components/use-select/use-select.ts
  packages/hooks/src/components/use-select/use-select.type.ts
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug, playground

#820 fix: 修复 `Image` 组件开启 `lazy` 后在 fixed 定位容器下检查交叉异常的问题
  package.json
  packages/hooks/src/utils/dom/element.tsx
  packages/hooks/src/utils/lazyload.ts
  packages/shineout/src/image/__doc__/changelog.cn.md
Labels: bug, playground

#821 fix: 修复 `Table` 动态添加行时，横向滚动条可能出现抖动的问题
  package.json
  packages/base/src/virtual-scroll/scroll.tsx
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: playground

#829 fix: 修复 `Form` 校验字段为嵌套字段时，自定义校验方法第二参数结构错误的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground
