Repository sheinsight/shineout-next, pull requests merged in 2025-07, with the labels that each got.

#1216 fix: 更新版本号至 3.7.5-beta.1，并修复 `Tooltip` 在 `Dropdown` 中使用时的 className传递问题
  package.json
  packages/base/src/dropdown/Item.tsx
  packages/shineout/src/tooltip/__doc__/changelog.cn.md
Labels: bug, playground

#1218 fix: 修复 `Dropdown` 组件在开启 `hover` 模式时鼠标移入非 dom 包含关系元素导致意外触发打开列表的问题
  package.json
  packages/hooks/src/components/use-popup/use-popup.ts
  packages/shineout/src/modal/__doc__/changelog.cn.md
Labels: bug, playground

#1219 fix: 修复 `Form` 卸载携带校验错误字段后，重新挂载该字段时会携带历史校验错误信息的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground, keep

#1220 fix: 更新版本号至 3.7.5-beta.5，并修复 `DatePicker` 组件的 `formatResult` 属性在 `type` 为 `month` 时切换月份时展示结果不正确的问题
  package.json
  packages/hooks/src/components/use-datepicker/use-datepicker-format.ts
  packages/shineout/package.json
  packages/shineout/src/date-picker/__doc__/changelog.cn.md
  pnpm-lock.yaml
Labels: bug, playground

#1223 fix: 修复 `Tree` 开启 `virtual` 后根节点样式缩进与非虚拟列表不一致的问题
  package.json
  packages/base/src/tree/tree-virtual-node.tsx
  packages/shineout/src/tree/__doc__/changelog.cn.md
Labels: bug, playground

#1224 fix: 优化 `Cascader` 的 `compressed` 属性在大数据场景下的性能表现，解决了在3000+选项时INP指标超过1000ms的性能问题
  package.json
  packages/base/src/cascader/node.tsx
  packages/base/src/select/result-more.tsx
  packages/base/src/select/result-more.type.ts
  packages/base/src/select/result.tsx
  packages/shineout/src/cascader/__doc__/changelog.cn.md
Labels: bug, playground, performance

#1225 fix: 修复 `Alert` 传入空字符串 `title` 属性也能渲染结构的问题
  package.json
  packages/base/src/alert/alert.tsx
  packages/shineout/src/alert/__doc__/changelog.cn.md
Labels: bug, playground, keep

#1226 fix: 更新版本号至 3.7.5-beta.11，新增 `compressedBoundWrapper` 样式，优化 `Select` 组件在大数据场景下的初始化性能
  package.json
  packages/base/src/cascader/cascader.type.ts
  packages/base/src/select/result.tsx
  packages/base/src/select/result.type.ts
  packages/base/src/select/select.type.ts
  packages/base/src/tree-select/tree-select.type.ts
  packages/shineout-style/src/cascader/cascader.ts
  packages/shineout-style/src/select/select.ts
  packages/shineout-style/src/tree-select/tree-select.ts
  packages/shineout/src/cascader/__example__/big-biz-data.js
  packages/shineout/src/cascader/__example__/test-02-virtual-compressed.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: performance

#1229 fix: 修复 `Textarea` 在 flex 容器中使用时，可能存在的内部textarea元素与外部容器高度不一致的问题
  package.json
  packages/shineout-style/src/textarea/textarea.ts
  packages/shineout/src/textarea/__doc__/changelog.cn.md
Labels: bug, playground

#1230 feat: 更新版本号至 3.8.0-beta.10，优化 `Radio` 和 `Checkbox` 的选中动画效果
  docs/markdown/shineout/changelog-common.md
  package.json
  packages/shineout-style/src/checkbox/checkbox.ts
  packages/shineout-style/src/common/common.ts
  packages/shineout-style/src/radio/radio.ts
Labels: enhancement

#1232 fix: 修复 `Select` 开启 `highlight` 后在 `renderItem` 中渲染非单层 dom 结构功能失效的问题
  package.json
  packages/hooks/src/utils/highlight.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug, playground

#1234 feat: `Breadcrumb` 设置 `max` 属性后，新增Popover展示完整菜单路径
  package.json
  packages/base/src/breadcrumb/breadcrumb-item.tsx
  packages/base/src/breadcrumb/breadcrumb.tsx
  packages/base/src/breadcrumb/breadcrumb.type.ts
  packages/shineout-style/src/breadcrumb/breadcrumb.ts
  packages/shineout-style/src/tooltip/tooltip.ts
  packages/shineout/src/breadcrumb/__doc__/changelog.cn.md
  packages/shineout/src/breadcrumb/__example__/02-separator.tsx
  packages/shineout/src/breadcrumb/__example__/06-max.tsx
  packages/shineout/src/breadcrumb/__test__/__snapshots__/breadcrumb.spec.tsx.snap
  packages/shineout/src/breadcrumb/breadcrumb.tsx
Labels: enhancement, playground

#1235 fix: Avatar api文档新增onClick类型
  docs/api/shineout/avatar.ts
  packages/base/src/avatar/avatar.type.ts
  packages/base/src/avatar/group.tsx
  packages/shineout/src/avatar/__example__/01-base.tsx
Labels: bug, documentation

#1236 fix: update changelog
  docs/markdown/shineout/changelog-v3.md
  docs/markdown/shineout/migration.md
Labels: documentation

#1240 feat: Sticky 新增 `stickyBoundary` 属性以支持在指定位置取消吸附
  docs/api/shineout/sticky.ts
  package.json
  packages/base/src/sticky/sticky.tsx
  packages/base/src/sticky/sticky.type.ts
  packages/shineout/src/sticky/__doc__/changelog.cn.md
  packages/shineout/src/sticky/__example__/04-sticky-boundary.tsx
  packages/shineout/src/sticky/__example__/t-02-auto-sticky.tsx
Labels: feature, playground

#1245 fix: 更新版本至 3.7.7-beta.3，修复 `Input` 组件的 `autoSelect` 属性在某些场景下无法自动选中所有文本的问题
  package.json
  packages/hooks/src/components/use-input/use-input.ts
  packages/shineout/src/input/__doc__/changelog.cn.md
Labels: bug, playground

#1249 fix: 更新版本至 3.7.7-beta.6，修复 `Table` 组件在动态高度情况下，虚拟列表最后一条数据显示不全的问题
  package.json
  packages/base/src/table/table.tsx
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug, playground

#1250 fix: 更新版本至 3.7.7-beta.7，修复 `Table` 组件的 `scrollToIndex` 方法滚动位置计算不准确的问题
  package.json
  packages/base/src/table/table.tsx
  packages/hooks/src/components/use-table/use-table-virtual.tsx
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__example__/07-02-virtual-scroll.tsx
Labels: bug, playground

#1251 fix: 修复Select compressed初始化时第一项结果都不显示,而是显示more 的Tag
  packages/base/src/select/result-more.tsx
  packages/shineout/src/cascader/__test__/__snapshots__/cascader.spec.tsx.snap
  packages/shineout/src/select/__test__/__snapshots__/select.spec.tsx.snap
  packages/shineout/src/tree-select/__test__/__snapshots__/treeSelect.spec.tsx.snap
Labels: bug, playground

#1254 refactor: jss-insertion-point元素从meta修改为style
  docs/markdown/shineout/changelog-common.md
  package.json
  packages/shineout-style/src/normalize.ts
Labels: performance

#1255 chore: release 3.7.7
  package.json
  packages/shineout-style/src/version.ts
  packages/shineout/src/index.ts
Labels: merge

#1257 fix: 修复 `Form` 对 `onChange` 的返回值直接修改数据后再设置新 value 不生效的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1256 chore: 更新 README 文件中的 React 版本要求，从 16.8.0 升级至 16.14.0
  README-zh_CN.md
  README.md
  package.json
  packages/base/package.json
  packages/hooks/package.json
  packages/shineout/package.json
Labels: documentation, performance

#1259 feat: `DatePicker` 增强 `disabledTime` 在开启 `range` 且为函数模式下的返回参数
  package.json
  packages/base/src/date-picker/date-picker.type.ts
  packages/base/src/date-picker/day.tsx
  packages/base/src/date-picker/time.tsx
  packages/hooks/src/components/use-datepicker/use-time.tsx
  packages/hooks/src/components/use-datepicker/use-time.type.ts
  packages/shineout/src/date-picker/__doc__/changelog.cn.md
Labels: enhancement

#1261 fix: 修复 `Tree` 动态数据时，存在 children 为 undefined 导致报错的问题
  package.json
  packages/hooks/src/components/use-tree/use-tree.ts
  packages/shineout/src/tree/__doc__/changelog.cn.md
Labels: bug

#1262 fix: 修复 `Dropdown` 的 `trigger` 为 `hover` 且设置 `absolute` 时，鼠标移入下拉框后下拉框…
  package.json
  packages/hooks/src/components/use-popup/use-popup.ts
  packages/shineout/src/dropdown/__doc__/changelog.cn.md
Labels: bug, playground

#1267 fix: 修复 `Select` 过滤过程中受 `trim` 属性影响，表现与老版本不一致的问题
  package.json
  packages/base/src/select/select.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug, playground, keep

#1270 fix: 修复 `Pagination` 的 `select` 下拉框在限制了高度的html或body滚动容器中第一次点击不出现的问题
  package.json
  packages/hooks/src/common/use-position-style/index.ts
  packages/hooks/src/utils/dom/document.ts
  packages/shineout/src/pagination/__doc__/changelog.cn.md
Labels: bug

#1274 chore: 更新版本至 3.7.8-beta.12，并修复 `Select` 组件在开启 `columns` 时的内边距样式问题
  package.json
  packages/base/src/select/list-columns.tsx
  packages/shineout-style/src/select/select.ts
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug, playground

#1278 fix: 修复 `Table` 在数据为空时，底部总结行依然会展示，表现与 v1 v2 不一致的问题
  package.json
  packages/base/src/table/table.tsx
  packages/base/src/table/tfoot.tsx
  packages/base/src/table/tfoot.type.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug, playground, keep

#1279 fix: 修复 `Sticky` 在非CSS模式下用户传入的 `zIndex` 样式未应用到最外层容器的问题
  .gitignore
  package.json
  packages/base/src/sticky/sticky.tsx
  packages/shineout/src/sticky/__doc__/changelog.cn.md
Labels: bug, playground

#1280 fix: 修复 Table 虚拟列表模式下合并行 checkbox 状态丢失的问题
  package.json
  packages/base/src/table/table.tsx
  packages/base/src/table/tbody.tsx
  packages/base/src/table/tbody.type.ts
  packages/base/src/table/tr.tsx
  packages/hooks/src/components/use-table/use-table-virtual.tsx
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug, playground

#1281 feat: `Form` 的 `FormRef` 新增 `getFormSchema` 方法，用于获取表单结构的标准 JSON Schema
  docs/api/shineout/form.ts
  package.json
  packages/base/src/form/form-field.tsx
  packages/base/src/form/form-item.tsx
  packages/base/src/form/form.tsx
  packages/base/src/form/form.type.ts
  packages/base/src/textarea/simple-textarea.tsx
  packages/hooks/src/components/use-form/Provider.tsx
  packages/hooks/src/components/use-form/form-schema-context.ts
  packages/hooks/src/components/use-form/index.ts
  packages/hooks/src/components/use-form/use-form-context.type.ts
  packages/hooks/src/components/use-form/use-form-item/form-item-context.ts
  packages/hooks/src/components/use-form/use-form-item/index.ts
  packages/hooks/src/components/use-form/use-form-schema/form-schema-builder.ts
  packages/hooks/src/components/use-form/use-form-schema/index.ts
  packages/hooks/src/components/use-form/use-form.ts
  packages/hooks/src/components/use-form/use-form.type.ts
  packages/hooks/src/utils/dom/element.tsx
  packages/shineout/src/date-picker/date-picker.tsx
  packages/shineout/src/form/__doc__/changelog.cn.md
  packages/shineout/src/form/__example__/test-001-base-form.tsx
  packages/shineout/src/rate/rate.tsx
  packages/shineout/src/select/select.tsx
Labels: documentation, feature

#1282 feat: 增强 Empty 组件 icon 和 description 属性支持全局配置
  docs/markdown/shineout/config.md
  package.json
  packages/base/src/config/index.ts
  packages/base/src/empty/empty-image.tsx
  packages/base/src/empty/empty.tsx
  packages/base/src/empty/empty.type.ts
  packages/base/src/icons/config.tsx
  packages/base/src/icons/icons.tsx
  packages/shineout/src/empty/__doc__/changelog.cn.md
Labels: enhancement
