Repository sheinsight/shineout-next, pull requests merged in 2025-05, with the labels that each got.

#1097 fix: 优化文档的api跳转
  docs/theme/components/markdown/api.tsx
Labels: documentation

#1100 feat: 新增 Skeleton 组件
  docs/api/shineout/skeleton.ts
  docs/api/shineout/sticky.ts
  docs/api/shineout/tabs.ts
  docs/markdown/shineout/changelog-common.md
  packages/base/src/index.ts
  packages/base/src/skeleton/__doc__/index.md
  packages/base/src/skeleton/__example__/01-base.tsx
  packages/base/src/skeleton/button.tsx
  packages/base/src/skeleton/image.tsx
  packages/base/src/skeleton/index.ts
  packages/base/src/skeleton/skeleton.tsx
  packages/base/src/skeleton/skeleton.type.ts
  packages/base/src/skeleton/text.tsx
  packages/shineout-style/src/index.ts
  packages/shineout-style/src/skeleton/index.ts
  packages/shineout-style/src/skeleton/skeleton.ts
  packages/shineout-style/src/version.ts
  packages/shineout/src/index.ts
  packages/shineout/src/skeleton/__doc__/guide.cn.md
  packages/shineout/src/skeleton/__doc__/guide.en.md
  packages/shineout/src/skeleton/__doc__/index.md
  packages/shineout/src/skeleton/__example__/01-base.tsx
  packages/shineout/src/skeleton/__example__/02-animation.tsx
  packages/shineout/src/skeleton/__example__/03-element.tsx
  packages/shineout/src/skeleton/__example__/04-combination.tsx
  packages/shineout/src/skeleton/index.ts
  packages/shineout/src/skeleton/interface.ts
  packages/shineout/src/skeleton/skeleton.tsx
  packages/shineout/src/skeleton/skeleton.type.ts
  packages/shineout/src/type.ts
  packages/theme/src/index.ts
  packages/theme/src/skeleton/index.ts
  packages/theme/src/skeleton/rule.ts
  packages/theme/src/skeleton/skeleton.ts
  packages/theme/src/skeleton/token.ts
  packages/theme/src/skeleton/type.ts
  scripts/ejs/shineout/component.type.ts.ejs
Labels: feature

#1104 feat: `Upload` 新增 `beforeDrop` 属性，支持自行处理拖拽释放事件以及读取文件列表处理返回文件
  package.json
  packages/base/src/upload/drop.tsx
  packages/base/src/upload/upload.tsx
  packages/base/src/upload/upload.type.ts
  packages/shineout/src/upload/__doc__/changelog.cn.md
Labels: feature

#1105 fix: 修复 `Select`、`TreeSelect`、`Cascader` 结果框高度不继承的问题
  package.json
  packages/shineout-style/src/cascader/cascader.ts
  packages/shineout-style/src/select/select.ts
  packages/shineout-style/src/tree-select/tree-select.ts
  packages/shineout/src/cascader/__doc__/changelog.cn.md
  packages/shineout/src/select/__doc__/changelog.cn.md
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
Labels: bug

#1103 fix: 增加Cascader 全选用法示例
  packages/base/src/cascader/cascader.tsx
  packages/shineout/src/cascader/__example__/11-render-option-list.tsx
Labels: bug, documentation

#1106 fix: 更新 FormRef 的 set 方法，支持 options 参数以增强字段值设置功能
  package.json
  packages/base/src/form/form.type.ts
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1107 fix: 更新 DatePicker 组件，修复受控用法下 onChange 多次调用的问题
  package.json
  packages/base/src/date-picker/date-picker.tsx
  packages/hooks/src/components/use-popup/use-popup.ts
  packages/shineout/src/date-picker/__doc__/changelog.cn.md
Labels: bug, playground

#1112 feat: `Table` 的 columns 新增 `groupProps` 属性，支持设置 style 和 className
  docs/api/shineout/table.ts
  package.json
  packages/base/src/table/thead.tsx
  packages/hooks/src/components/use-table/use-table-group.ts
  packages/hooks/src/components/use-table/use-table.type.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__example__/04-group.tsx
  packages/shineout/src/table/__test__/__snapshots__/table.spec.tsx.snap
Labels: feature

#1114 fix: 修复 `Button` 在React 18以下初始化时有过渡动画的问题
  package.json
  packages/shineout-style/src/button/button.ts
  packages/shineout/src/button/__doc__/changelog.cn.md
Labels: bug

#1115 fix: 修复 `Form` 在列表数据中使用时，列表数据更新导致校验状态丢失的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1118 fix: 修复 `Tree` 在 data 发生变化后 `defaultExpanded` 不生效的问题
  package.json
  packages/base/src/tree/tree.tsx
  packages/hooks/src/components/use-tree/use-tree.ts
  packages/hooks/src/components/use-tree/use-tree.type.ts
  packages/shineout/src/tree/__doc__/changelog.cn.md
Labels: bug, playground

#1119 fix: 修复 `Tree` 在开启虚拟列表后 `data` 为 undefined 时可能存在死循环的问题
  package.json
  packages/hooks/src/components/use-tree/use-tree.ts
  packages/shineout/src/tree/__doc__/changelog.cn.md
Labels: bug, playground

#1123 fix: 修复 `Form` 在设置动态 `name` 情况下导致字段可能被删除的问题
  package.json
  packages/hooks/src/components/use-form/use-form-control/use-form-control.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1126 feat: `Select` 新增 `highlight` 属性，是否开启搜索关键字高亮功能
  docs/api/shineout/cascader.ts
  docs/api/shineout/select.ts
  docs/api/shineout/tree-select.ts
  docs/theme/locales/en-US.ts
  package.json
  packages/base/src/cascader/cascader.tsx
  packages/base/src/cascader/cascader.type.ts
  packages/base/src/cascader/filter-list.type.ts
  packages/base/src/cascader/filter-node.tsx
  packages/base/src/cascader/list.type.ts
  packages/base/src/cascader/node.tsx
  packages/base/src/common/type.ts
  packages/base/src/index.ts
  packages/base/src/select/list-option.tsx
  packages/base/src/select/select.tsx
  packages/base/src/select/select.type.ts
  packages/base/src/tree-select/tree-select.tsx
  packages/base/src/tree-select/tree-select.type.ts
  packages/base/src/tree/tree-content.tsx
  packages/base/src/tree/tree.type.ts
  packages/hooks/src/common/use-filter/index.ts
  packages/hooks/src/common/use-filter/use-filter-context.ts
  packages/hooks/src/common/use-filter/use-filter.ts
  packages/hooks/src/utils/highlight.tsx
  packages/hooks/src/utils/index.ts
  packages/hooks/src/utils/string.ts
  packages/shineout-style/src/common/common.ts
  packages/shineout-style/src/common/index.ts
  packages/shineout-style/src/index.ts
  packages/shineout-style/src/radio/radio.ts
  packages/shineout-style/src/switch/switch.ts
  packages/shineout/src/cascader/__doc__/changelog.cn.md
  packages/shineout/src/cascader/__example__/06-01-filter.tsx
  packages/shineout/src/cascader/__example__/06-02-filter.tsx
  packages/shineout/src/cascader/__test__/__snapshots__/cascader.spec.tsx.snap
  packages/shineout/src/cascader/cascader.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
  packages/shineout/src/select/__example__/10-01-filter.tsx
  packages/shineout/src/select/__test__/__snapshots__/select.spec.tsx.snap
  packages/shineout/src/select/select.tsx
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
  packages/shineout/src/tree-select/__example__/04-01-filter.tsx
  packages/shineout/src/tree-select/__test__/__snapshots__/treeSelect.spec.tsx.snap
  packages/shineout/src/tree-select/tree-select.tsx
  packages/shineout/src/tree/tree.tsx
Labels: feature

#1127 fix: 修复 `Form` 在相同 `name` 的组件切换渲染过程中，执行 `datum.set` 等改值行为失效的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/hooks/src/components/use-form/use-form.type.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1134 feat: `List` 新增 `loadingPosition` 属性，设置为bottom后在列表底部显示加载图标
  docs/api/shineout/list.ts
  packages/base/src/list/list.tsx
  packages/base/src/list/list.type.ts
  packages/shineout-style/src/list/list.ts
  packages/shineout/src/list/__doc__/changelog.cn.md
  packages/shineout/src/list/__example__/08-load-scroll-bottom.tsx
Labels: feature

#1135 fix: 修复 `Radio.Group` 在文案过长情况下小圆点选择器样式被挤压异常的问题
  package.json
  packages/shineout-style/src/radio/radio.ts
  packages/shineout/src/radio/__doc__/changelog.cn.md
Labels: bug, playground

#1136 feat: `Carousel` 新增 `showIndicator` 和 `itemClassName` 属性
  package.json
  packages/base/src/carousel/carousel.tsx
  packages/base/src/carousel/carousel.type.ts
  packages/shineout/src/carousel/__doc__/changelog.cn.md
Labels: feature
