Repository sheinsight/shineout-next, pull requests merged in 2025-03, with the labels that each got.

#981 fix: 修复 `TreeSelect` 过滤筛选情况下选择数据不完整的问题
  package.json
  packages/base/src/tree-select/tree-select.tsx
  packages/base/src/tree/tree.tsx
  packages/base/src/tree/tree.type.ts
  packages/hooks/src/components/use-tree/use-tree.ts
  packages/hooks/src/components/use-tree/use-tree.type.ts
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
  packages/shineout/src/tree-select/__example__/10-virtual.tsx
  packages/shineout/src/tree/__example__/12-virtual.tsx
Labels: bug

#982 fix: 修复 `Image` 在容器为 'absolute' 定位情况下 `lazy` 属性可能失效的问题
  package.json
  packages/hooks/src/utils/dom/element.tsx
  packages/hooks/src/utils/lazyload.ts
  packages/shineout/src/date-picker/__test__/datePicker.spec.tsx
  packages/shineout/src/image/__doc__/changelog.cn.md
Labels: bug, playground

#983 fix: 修复 `Datepicker` 仅开启 `needConfirm` 属性情况下不展示今天按钮的问题、调整小尺寸日期组件样式
  package.json
  packages/base/src/date-picker/day.tsx
  packages/shineout-style/src/date-picker/date-picker.ts
  packages/shineout/src/date-picker/__doc__/changelog.cn.md
  packages/theme/src/date-picker/date-picker.ts
  packages/theme/src/date-picker/token.ts
  packages/theme/src/date-picker/type.ts
Labels: bug, playground

#993 feat: `Upload` 组件新增 `hideHandler` 属性、`Image` 组件新增 `customRenderHoverMask` 属性
  package.json
  packages/base/src/image/image.tsx
  packages/base/src/image/image.type.ts
  packages/base/src/image/index.ts
  packages/base/src/upload/upload.tsx
  packages/base/src/upload/upload.type.ts
  packages/shineout/src/image/__doc__/changelog.cn.md
  packages/shineout/src/image/image.type.ts
  packages/shineout/src/upload/__doc__/changelog.cn.md
Labels: enhancement, feature

#996 fix: 修复 `Upload.Dragger` 子组件缺失的问题
  package.json
  packages/base/src/upload/dragger.tsx
  packages/base/src/upload/dragger.type.ts
  packages/base/src/upload/index.ts
  packages/base/src/upload/upload.type.ts
  packages/shineout-style/src/upload/upload.ts
  packages/shineout/src/upload/__doc__/changelog.cn.md
  packages/shineout/src/upload/dragger.tsx
  packages/shineout/src/upload/dragger.type.ts
  packages/shineout/src/upload/index.ts
  packages/shineout/src/upload/interface.ts
Labels: bug

#999 fix: 修复`Cascader` mode=0时，外部动态修改data后导致的选中结果与勾选的显示情况不一致的问题
  package.json
  packages/hooks/src/components/use-tree/use-tree.ts
  packages/shineout-style/src/table/table.ts
  packages/shineout/src/cascader/__doc__/changelog.cn.md
Labels: bug, playground

#1001 fix: 修复 `TreeSelect` 组件开 `virtual` 和 `defaultExpandedAll` 后，过滤数据不展开的问题、节点样式不对齐对问题
  docs/theme/components/example/style.ts
  package.json
  packages/base/src/tree-select/tree-select.tsx
  packages/base/src/tree/tree.tsx
  packages/base/src/tree/tree.type.ts
  packages/hooks/src/components/use-tree/use-tree.ts
  packages/shineout-style/src/tree/tree.ts
  packages/shineout/src/tree-select/__example__/10-virtual.tsx
  packages/shineout/src/tree/__doc__/changelog.cn.md
Labels: bug

#1002 fix: DatePicker & Pagination
  package.json
  packages/base/src/date-picker/date-picker.type.ts
  packages/base/src/date-picker/day.tsx
  packages/base/src/date-picker/result.tsx
  packages/base/src/pagination/pagination-jumper.tsx
  packages/base/src/pagination/pagination-jumper.type.ts
  packages/base/src/pagination/pagination.tsx
  packages/hooks/src/components/use-datepicker/use-datepicker-format.ts
  packages/hooks/src/components/use-datepicker/use-datepicker-format.type.ts
  packages/hooks/src/components/use-popup/use-popup.ts
  packages/shineout/src/date-picker/__doc__/changelog.cn.md
  packages/shineout/src/date-picker/__example__/09-select-confirm.tsx
  packages/shineout/src/date-picker/__test__/datePicker.spec.tsx
  packages/shineout/src/dropdown/__example__/009-icon.tsx
  packages/shineout/src/link/__example__/05-icon.tsx
  packages/shineout/src/pagination/__test__/__snapshots__/pagination.spec.tsx.snap
Labels: bug, enhancement, playground

#1008 fix: 修复 `Transfer` 设置了 `renderFilter` 之后可能导致左右面板高度不一致的问题
  docs/theme/layout/desktop/style.ts
  package.json
  packages/base/src/transfer/transfer-list.tsx
  packages/shineout-style/src/input/input-border.ts
  packages/shineout/src/input/__example__/04-01-group.tsx
  packages/shineout/src/input/__example__/04-03-group-validate.tsx
  packages/shineout/src/input/__test__/__snapshots__/input.spec.tsx.snap
  packages/shineout/src/select/__example__/17-custom-result-1.tsx
  packages/shineout/src/select/__example__/17-custom-result-2.tsx
  packages/shineout/src/select/__test__/select.spec.tsx
  packages/shineout/src/transfer/__doc__/changelog.cn.md
Labels: bug, documentation, playground

#1012 fix: 修复 `Table` 的columns是动态值时，column.filter的过滤功能意外的被重置的问题
  package.json
  packages/hooks/src/components/use-table/use-table-filter.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__test__/table.spec.tsx
Labels: bug

#1014 fix: 修复 `Input.Group` 下面的 `Input` 的 `onBlur` 和 `onFocus` 回调函数的参数格式不正确的问题
  packages/base/src/input/input-group.tsx
  packages/shineout/src/input/__doc__/changelog.cn.md
Labels: bug

#1013 fix: 修复 `Form` 同时设置 value 和 names为数组的DatePicker并发渲染时，value未按照预期设置进去的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
  packages/shineout/src/form/__example__/test-004-deley-0.tsx
Labels: bug, playground

#1016 fix: 优化 `CardGroup` 在非滚动容器下也能支持懒加载
  package.json
  packages/hooks/src/common/use-in-view/use-in-view.ts
  packages/hooks/src/utils/dom/element.tsx
  packages/shineout/src/card-group/__doc__/changelog.cn.md
Labels: enhancement

#1018 feat: 优化 `Popover` 的 `adjust` 属性，支持弹出层位置实时跟随父元素尺寸变化
  packages/hooks/src/common/use-position-style/check-position.ts
  packages/shineout/src/popover/__doc__/changelog.cn.md
Labels: enhancement, playground

#1019 feat: 优化 `Tooltip` 的箭头，支持动态修改内容后箭头的位置仍然正常
  packages/base/src/absolute-list/absolute-list.tsx
  packages/base/src/absolute-list/absolute-list.type.tsx
  packages/base/src/tooltip/tooltip.tsx
  packages/hooks/src/common/use-position-style/index.ts
  packages/hooks/src/components/use-popup/use-popup.ts
  packages/shineout-style/src/tooltip/tooltip.ts
  packages/shineout/src/tooltip/__doc__/changelog.cn.md
Labels: enhancement, playground

#1020 fix: 修复 `Tooltip` 的 `persistent` 配置优先级问题，使其优先于全局配置并符合就近原则
  packages/base/src/tooltip/tooltip.tsx
  packages/shineout/src/tooltip/__doc__/changelog.cn.md
Labels: bug

#1021 fix: 修复 `Input.Number` 输入“0.0”这种格式时小数点丢失的问题
  packages/hooks/src/components/use-input/use-input-number.ts
  packages/shineout/src/input/__doc__/changelog.cn.md
Labels: bug, playground

#1022 fix: 修复 `Card.Header` 和 `Card.Footer` 在未开启 `moveable` 属性时不可选中文本的问题
  package.json
  packages/base/src/card/card.tsx
  packages/shineout/src/card/__doc__/changelog.cn.md
Labels: bug

#1027 fix: 修复 `DatePicker` 的`date` 类型在开启 `inputable` 和 `range`之后，开始日期输入了比结束…
  packages/hooks/src/components/use-datepicker/use-datepicker-format.ts
  packages/shineout/src/date-picker/__doc__/changelog.cn.md
Labels: bug, playground
