Repository sheinsight/shineout-next, pull requests merged in 2025-04, with the labels that each got.

#1029 fix: 修复 `Input.Group` 属性 `seperate` 默认不生效的问题
  docs/api/shineout/alert.ts
  docs/api/shineout/checkbox.ts
  docs/api/shineout/date-picker.ts
  docs/api/shineout/image.ts
  docs/api/shineout/input.ts
  docs/api/shineout/tabs.ts
  package.json
  packages/base/src/input/input-group.tsx
  packages/base/src/input/input-group.type.ts
  packages/shineout-style/src/input/input-border.ts
  packages/shineout-style/src/input/input.ts
  packages/shineout/src/input/__doc__/changelog.cn.md
  packages/shineout/src/input/__example__/03-number-1.tsx
  packages/shineout/src/input/__test__/__snapshots__/input.spec.tsx.snap
  packages/shineout/src/input/__test__/input.spec.tsx
  packages/shineout/src/input/group.type.ts
  packages/shineout/src/input/input.type.ts
  packages/shineout/src/input/number.type.ts
  packages/shineout/src/input/password.type.ts
Labels: bug

#1033 fix: 修复 `Form.Field` 在 `name` 为数组情况下组件卸载时错误信息无法清空的问题
  packages/hooks/src/components/use-form/use-form-control/use-form-control.ts
Labels: bug, playground

#1032 feat: 新增 `Popover` 组件的 `disabled` 属性以支持禁用功能
  docs/api/shineout/popover.ts
  packages/base/src/popover/popover.tsx
  packages/base/src/popover/popover.type.ts
  packages/shineout/src/popover/__doc__/changelog.cn.md
  packages/shineout/src/popover/__example__/14-disabled.tsx
Labels: feature

#1023 feat: `Table` 新增缓存单元格功能：设置 `columns` 配置项的 `shouldUpdate` 属性
  docs/api/shineout/table.ts
  packages/base/src/icons/config.tsx
  packages/base/src/table/td.tsx
  packages/base/src/table/tr.tsx
  packages/base/src/tag/tag.tsx
  packages/hooks/src/common/use-memo/index.ts
  packages/hooks/src/common/use-memo/use-memo.ts
  packages/hooks/src/components/use-table/index.ts
  packages/hooks/src/components/use-table/use-table.type.ts
  packages/hooks/src/index.ts
  packages/shineout-style/src/version.ts
  packages/shineout/src/index.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__example__/test-009-should-cell-update.tsx
  packages/shineout/src/tag/__test__/__snapshots__/tag.spec.tsx.snap
Labels: feature

#1034 fix: 修正Form内部update行为(Regression: since v3.6.1-beta.4)
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__example__/test-004-deley-0.tsx
Labels: bug, playground

#1035 fix: 修复 `Transfer` 动态设置 `loading` 不生效的问题
  packages/base/src/transfer/transfer.tsx
  packages/shineout/src/transfer/__doc__/changelog.cn.md
Labels: bug

#1038 fix: 修复 `Input.Group` 的 `seperate` 在一些组合场景下的样式问题
  package.json
  packages/base/src/input/input-group.tsx
  packages/base/src/input/input-group.type.ts
  packages/shineout-style/src/button/button.ts
  packages/shineout-style/src/input/input-border.ts
  packages/shineout-style/src/input/input.ts
  packages/shineout/src/button/__example__/s-005-status.tsx
  packages/shineout/src/button/__test__/__snapshots__/button.spec.tsx.snap
  packages/shineout/src/button/__test__/button.spec.tsx
  packages/shineout/src/form/__example__/011-fieldset-loop.tsx
  packages/shineout/src/input/__doc__/changelog.cn.md
  packages/shineout/src/input/__example__/04-01-group.tsx
  packages/shineout/src/input/__example__/04-02-group-seperate.tsx
  packages/shineout/src/input/__example__/04-03-group-validate.tsx
  packages/shineout/src/input/__test__/__snapshots__/input.spec.tsx.snap
  packages/shineout/src/input/__test__/input.spec.tsx
Labels: bug

#1041 feat: 新增 `Cascader` 、`TreeSelect` 多选后尺寸相关 token
  docs/theme/layout/desktop/float/theme.ts
  packages/shineout-style/src/cascader/cascader.ts
  packages/shineout-style/src/tree-select/tree-select.ts
  packages/theme/src/cascader/cascader.ts
  packages/theme/src/cascader/token.ts
  packages/theme/src/cascader/type.ts
  packages/theme/src/tree-select/token.ts
  packages/theme/src/tree-select/tree-select.ts
  packages/theme/src/tree-select/type.ts
Labels: enhancement

#1042 chore: 示例文档的api能跳转至api页面
  docs/theme/components/example/index.tsx
  docs/theme/components/example/style.ts
  docs/theme/components/markdown/api.tsx
  docs/theme/components/markdown/doc.tsx
  docs/theme/components/style.ts
  packages/shineout/src/input/__example__/04-03-group-validate.tsx
  packages/shineout/src/tree/__example__/03-line.tsx
  packages/shineout/src/tree/__example__/04-02-expandall.tsx
  packages/shineout/src/tree/__example__/06-onchange.tsx
  packages/shineout/src/tree/__example__/08-drag.tsx
  packages/shineout/src/tree/__example__/09-drag-style.tsx
  packages/shineout/src/tree/__example__/10-inline-node.tsx
  packages/shineout/src/tree/__example__/11-action-on-click.tsx
  packages/shineout/src/tree/__example__/12-highlight.tsx
  packages/shineout/src/tree/__example__/13-highlight-control.tsx
  packages/shineout/src/tree/__example__/14-virtual.tsx
Labels: documentation

#1043 chore: 更新文档api跳转方式
  docs/theme/components/example/index.tsx
  docs/theme/components/example/style.ts
  docs/theme/components/example/tip/index.tsx
  packages/shineout/src/tree/__example__/03-line.tsx
  packages/shineout/src/tree/__example__/04-02-expandall.tsx
  packages/shineout/src/tree/__example__/06-onchange.tsx
  packages/shineout/src/tree/__example__/07-loader.tsx
  packages/shineout/src/tree/__example__/08-drag.tsx
  packages/shineout/src/tree/__example__/09-drag-style.tsx
  packages/shineout/src/tree/__example__/10-inline-node.tsx
  packages/shineout/src/tree/__example__/11-action-on-click.tsx
  packages/shineout/src/tree/__example__/12-highlight.tsx
  packages/shineout/src/tree/__example__/13-highlight-control.tsx
  packages/shineout/src/tree/__example__/14-virtual.tsx
Labels: documentation

#1046 fix: 优化 `Table` vitural模式下的固定列，提升滚动性能
  package.json
  packages/base/src/table/table.tsx
  packages/base/src/table/tbody.tsx
  packages/base/src/table/tbody.type.ts
  packages/base/src/table/tfoot.tsx
  packages/base/src/table/tfoot.type.ts
  packages/base/src/table/thead.tsx
  packages/base/src/table/thead.type.ts
  packages/base/src/table/tr.tsx
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__example__/07-02-virtual-scroll.tsx
  packages/shineout/src/table/__test__/table.spec.tsx
Labels: performance

#1048 fix: 修复 Sticky 组件 onChange 不触发的问题，更新版本号至 3.6.3-beta.1
  package.json
  packages/base/src/sticky/sticky.tsx
  packages/shineout/src/sticky/__doc__/changelog.cn.md
  packages/shineout/src/sticky/__example__/01-base.tsx
Labels: bug

#1050 Perf table
  package.json
  packages/base/src/table/table.tsx
  packages/base/src/table/table.type.ts
  packages/base/src/table/tbody.tsx
  packages/base/src/table/thead.tsx
  packages/base/src/table/tr.tsx
  packages/base/src/virtual-scroll/scroll-table.tsx
  packages/hooks/src/components/use-table/use-table-layout.tsx
  packages/hooks/src/components/use-table/use-table-row.tsx
  packages/hooks/src/components/use-table/use-table-virtual.tsx
  packages/shineout-style/src/table/table.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__test__/table.spec.tsx
Labels: bug, performance

#1045 fix: 修复 `Table` 的 tfoot 没有在底部吸附的问题（Regression： since v3.5.0）
  package.json
  packages/shineout-style/src/table/table.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug, playground

#1051 fix: 修复 `Cascader`、`TreeSelect` 最大高度限制失效的问题（默认 max-height 应为 80px）
  package.json
  packages/shineout-style/src/cascader/cascader.ts
  packages/shineout-style/src/tree-select/tree-select.ts
  packages/shineout/src/cascader/__doc__/changelog.cn.md
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
Labels: bug

#1052 fix: table draggable
  packages/base/src/icons/config.tsx
  packages/base/src/icons/icons.tsx
  packages/base/src/table/tbody.tsx
  packages/base/src/tag/tag.tsx
  packages/shineout/src/menu/__test__/__snapshots__/menu.spec.tsx.snap
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/tag/__test__/__snapshots__/tag.spec.tsx.snap
  packages/shineout/src/tree/__test__/__snapshots__/tree.spec.tsx.snap
Labels: bug

#1054 fix: 修复 `Modal` 多层嵌套使用时，关闭子Modal但未关闭父Modal时body的滚动条出现的问题
  package.json
  packages/base/src/modal/modal-content.tsx
  packages/shineout/src/modal/__doc__/changelog.cn.md
Labels: bug, playground

#1057 feat: Table新增shouldCellUpdate
  docs/api/shineout/table.ts
  docs/index.tsx
  packages/base/src/icons/config.tsx
  packages/base/src/table/table.tsx
  packages/base/src/table/tbody.tsx
  packages/base/src/table/tbody.type.ts
  packages/base/src/table/td.tsx
  packages/base/src/table/tr.tsx
  packages/base/src/tag/tag.tsx
  packages/hooks/src/components/use-table/index.ts
  packages/hooks/src/components/use-table/use-table.type.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__example__/07-02-virtual-scroll5.tsx
Labels: enhancement, feature

#1063 fix: 更新版本号至 3.6.4-beta.1，修复 `Modal` 多层嵌套使用时的滚动条问题
  package.json
  packages/shineout-style/src/modal/modal.ts
  packages/shineout/src/modal/__doc__/changelog.cn.md
Labels: bug, playground

#1064 fix: 修复 `Select` 搜索内容后选项被遮挡的问题
  packages/base/src/select/list.tsx
  packages/base/src/select/select.tsx
  packages/base/src/select/select.type.ts
Labels: bug, playground

#1066 fix: 修复 `Select` 开启过滤后打开面板快速再次聚焦时可能清空输入框文本内容的问题
  package.json
  packages/base/src/select/result.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug, playground

#1067 fix: 修复 `Form` 在ReactDOM.render模式下并发设置value后导致某些字段值丢失的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1069 fix: 优化 Popover 和 Tooltip 在窗口resize和父容器滚动后依然能跟随目标
  package.json
  packages/base/src/popover/popover.tsx
  packages/base/src/tooltip/tooltip.tsx
  packages/hooks/src/common/use-position-style/index.ts
  packages/shineout/src/popover/__doc__/changelog.cn.md
  packages/shineout/src/tooltip/__doc__/changelog.cn.md
Labels: enhancement

#1070 fix: 修复 `Cascader` 设置了expandTrigger为hover后切换高亮路径后但不选中值，二次打开面板时高亮路径与选中…
  package.json
  packages/base/src/cascader/cascader.tsx
  packages/shineout/src/cascader/__doc__/changelog.cn.md
  packages/shineout/src/cascader/__example__/03-01-trigger.tsx
Labels: bug

#1071 fix: 修复 `Tree` 传入 `rowsInView` 属性失效的问题
  packages/base/src/tree/tree-virtual.tsx
  packages/base/src/tree/tree.tsx
  packages/base/src/tree/tree.type.ts
  packages/shineout/src/tree/__doc__/changelog.cn.md
Labels: bug

#1074 fix: 优化 `Table` 的 `shouldCellUpdate` 缓存性能
  package.json
  packages/base/src/table/table.tsx
  packages/base/src/table/td.tsx
  packages/hooks/src/common/use-component-memo/index.ts
  packages/hooks/src/common/use-component-memo/use-memo.ts
  packages/hooks/src/common/use-memo/index.ts
  packages/hooks/src/components/use-table/use-table-virtual.tsx
  packages/hooks/src/index.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__example__/test-009-should-cell-update.tsx
Labels: performance

#1075 feat: `Tabs` 新增 `renderTabsHeader` 属性，支持自定义渲染头部内容
  package.json
  packages/base/src/tabs/tabs.tsx
  packages/base/src/tabs/tabs.type.ts
  packages/shineout/src/tabs/__doc__/changelog.cn.md
Labels: feature

#1076 fix: 修复 `TreeSelect` 在页面边界搜索时，下拉弹出层的位置未实时更新导致偏离父元素的问题
  packages/base/src/popover/popover.tsx
  packages/base/src/tooltip/tooltip.tsx
  packages/hooks/src/common/use-position-style/check-element-size.ts
  packages/hooks/src/common/use-position-style/index.ts
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
Labels: bug, playground

#1079 fix: 修复 `Select` 在 `Popover` 中使用并且开启了compressed属性后，点击compressed弹出层中的删…
  package.json
  packages/base/src/cascader/cascader.tsx
  packages/base/src/select/result-more.tsx
  packages/base/src/select/result-more.type.ts
  packages/base/src/select/result.tsx
  packages/base/src/select/result.type.ts
  packages/base/src/select/select.tsx
  packages/base/src/tree-select/tree-select.tsx
  packages/shineout-style/src/cascader/cascader.ts
  packages/shineout-style/src/select/select.ts
  packages/shineout-style/src/tree-select/tree-select.ts
  packages/shineout/src/cascader/__doc__/changelog.cn.md
  packages/shineout/src/select/__doc__/changelog.cn.md
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
Labels: bug

#1080 fix: 优化 `Image` 默认的`fill`实现方式，改善大图片在Chrome浏览器下的性能
  package.json
  packages/base/src/image/image.tsx
  packages/hooks/src/components/use-image/use-image.ts
  packages/shineout-style/src/image/image.ts
  packages/shineout/src/image/__doc__/changelog.cn.md
  packages/shineout/src/image/__test__/__snapshots__/image.spec.tsx.snap
  packages/shineout/src/image/__test__/image.spec.tsx
Labels: enhancement

#1082 fix: 修复 `Upload` 多选文件并发上传时偶现的结果丢失问题
  package.json
  packages/hooks/src/common/use-input-able/use-Input-able.ts
  packages/hooks/src/components/use-upload/use-upload.ts
  packages/shineout/src/upload/__doc__/changelog.cn.md
Labels: bug

#1088 fix: 更新版本号至 3.6.5-beta.10，并修复useForm组件的isControl属性逻辑
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/upload/__doc__/changelog.cn.md
Labels: bug

#1089 fix: 修复 `Transfer` 自定义children时左右勾选互斥的问题，并修正children的 `onSelect` ts类型
  package.json
  packages/base/src/transfer/transfer-list.type.ts
  packages/base/src/transfer/transfer.tsx
  packages/base/src/transfer/transfer.type.ts
  packages/shineout/src/transfer/__doc__/changelog.cn.md
Labels: bug, playground

#1090 fix: 修复Modal.Submit的onClick事件比form.submit先执行的问题
  package.json
  packages/base/src/form/form-footer-context.tsx
  packages/base/src/modal/modal-submit.tsx
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/card/__test__/card.spec.tsx
  packages/shineout/src/modal/__doc__/changelog.cn.md
Labels: bug, playground

#1092 fix: 更新版本号至3.7.0-beta.13，并移除Table不必要的scrollContainer属性
  package.json
  packages/base/src/table/table.tsx
  packages/base/src/table/table.type.ts
  packages/shineout/src/table/__example__/06-bottom-scrollbar.tsx
Labels: bug

#1093 perf: Table virtual="lazy" 滚动过程中不触发渲染
  docs/api/shineout/table.ts
  packages/base/src/table/table.tsx
  packages/base/src/table/table.type.ts
  packages/base/src/table/tbody.tsx
  packages/base/src/table/tbody.type.ts
  packages/base/src/table/td.tsx
  packages/base/src/table/tr.tsx
  packages/hooks/src/common/use-component-memo/index.ts
  packages/hooks/src/common/use-component-memo/use-memo.ts
  packages/hooks/src/components/use-table/index.ts
  packages/hooks/src/components/use-table/use-table.type.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
  packages/shineout/src/table/__example__/07-02-virtual-scroll5.tsx
  packages/shineout/src/table/__example__/test-009-should-cell-update.tsx
Labels: performance

#1094 fix: 修复 `Tabs.Panel` 设置 `background` 非预期的影响到shape为button和fill的样式（Regression: since v3.6.2）
  package.json
  packages/base/src/tabs/tabs-panel.tsx
  packages/shineout-style/src/modal/modal.ts
  packages/shineout/src/tabs/__doc__/changelog.cn.md
  packages/shineout/src/transfer/__doc__/changelog.cn.md
Labels: bug, playground
