Repository sheinsight/shineout-next, pull requests merged in 2025-06, with the labels that each got.

#1138 fix: ui issues fix
  packages/base/src/icons/icons.tsx
  packages/base/src/table/thead-filter.tsx
  packages/base/src/tree/tree-content.tsx
  packages/hooks/src/components/use-table/use-table.type.ts
  packages/shineout/src/table/__example__/09-001-filter-column.tsx
  packages/theme/src/modal/modal.ts
  packages/theme/src/modal/token.ts
  packages/theme/src/modal/type.ts
Labels: bug

#1140 fix: 修复Table前端过滤多选的勾选状态在重置后未清空的问题
  packages/base/src/table/thead-filter.tsx
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug

#1139 fix: 修复 `Carousel` 自定义指示器时，轮播数量为1条时不渲染的问题
  package.json
  packages/base/src/carousel/carousel.tsx
  packages/shineout/src/carousel/__doc__/changelog.cn.md
Labels: bug

#1146 fix: 修复 `Table` 的data引用不变但数据变化后，组件不触发更新的问题
  package.json
  packages/hooks/src/components/use-table/use-table-filter.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug

#1152 fix: 移除use-form.type.ts中的无用属性settingMap
  packages/hooks/src/components/use-form/use-form.type.ts
Labels: bug

#1154 fix: 修复 `Select` 设置了 `absolute` 用法下，在某些位置打开下拉框时有多余的过渡动画问题
  package.json
  packages/hooks/src/common/use-position-style/index.ts
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug

#1155 fix: 修复 `Table` 单元格中使用的 Popover 设置的挂载容器在 td 元素内时的遮挡问题
  package.json
  packages/shineout-style/src/table/table.ts
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug

#1156 feat: `TreeSelect` 增强 `disabled` 属性，支持动态 disabled
  package.json
  packages/base/src/tree-select/tree-select.tsx
  packages/base/src/tree-select/tree-select.type.ts
  packages/base/src/tree/tree.tsx
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
Labels: enhancement

#1164 fix: 更新版本号至 3.7.1-beta.9，修复 `Select` 组件在 `Drawer` 中使用并开启 compressed 属…
  package.json
  packages/base/src/select/result.tsx
  packages/shineout/src/select/__doc__/changelog.cn.md
Labels: bug, playground

#1166 chore: release 3.7.1
  package.json
Labels: merge

#1165 fix: 修复 `Cascader` 多选模式下末级叶子节点未高亮的问题
  package.json
  packages/base/src/cascader/list.tsx
  packages/base/src/cascader/node.tsx
  packages/base/src/cascader/node.type.ts
  packages/shineout/src/cascader/__doc__/changelog.cn.md
Labels: bug

#1168 feat: 优化 `Upload` 上传结果的样式，移除了成功和失败状态的图标
  package.json
  packages/base/src/upload/result.tsx
  packages/base/src/upload/upload.type.ts
  packages/shineout-style/src/upload/upload.ts
  packages/shineout/src/upload/__doc__/changelog.cn.md
  packages/shineout/src/upload/__example__/test-02-form-error.tsx
  packages/shineout/src/upload/__test__/__snapshots__/upload.spec.tsx.snap
  packages/shineout/src/upload/__test__/upload.spec.tsx
  packages/theme/src/common/common.ts
  packages/theme/src/common/type.ts
  packages/theme/src/token/figma.js
  packages/theme/src/token/token.ts
  packages/theme/src/token/type.ts
  packages/theme/src/upload/token.ts
  packages/theme/src/upload/type.ts
  packages/theme/src/upload/upload.ts
Labels: enhancement

#1170 fix: 修复 `Modal` 组件在被外部卸载后无法重置 HTML 元素样式的问题
  package.json
  packages/base/src/modal/modal-content.tsx
  packages/shineout/src/modal/__doc__/changelog.cn.md
Labels: bug, playground

#1172 fix: 修复 TreeSelect 开启 virtual 后传入 undefined 数据导致死循环问题、Upload.Button 传入 drop 属性失效的问题
  package.json
  packages/base/src/tree-select/tree-select.tsx
  packages/base/src/upload/button.tsx
  packages/base/src/upload/button.type.ts
  packages/shineout/src/tree-select/__doc__/changelog.cn.md
Labels: bug, keep

#1173 chore: 更新版本号至 3.8.0-beta.2，增强 `Popover` 和 `Tooltip` 组件的弹出动画效果
  package.json
  packages/hooks/src/common/use-position-style/index.ts
  packages/shineout-style/src/popover/popover.ts
  packages/shineout-style/src/tooltip/tooltip.ts
  packages/shineout/src/popover/__doc__/changelog.cn.md
  packages/shineout/src/popover/__test__/__snapshots__/popover.spec.tsx.snap
  packages/shineout/src/popover/__test__/popover.spec.tsx
  packages/shineout/src/tooltip/__doc__/changelog.cn.md
  packages/shineout/src/tooltip/__test__/tooltip.spec.tsx
Labels: enhancement, feature

#1174 feat: `Transfer` 新增 `highlight` 属性，开启搜索关键字高亮功能
  docs/api/shineout/transfer.ts
  package.json
  packages/base/src/transfer/transfer-list-item.tsx
  packages/base/src/transfer/transfer-list-item.type.ts
  packages/base/src/transfer/transfer.tsx
  packages/base/src/transfer/transfer.type.ts
  packages/hooks/src/components/use-transfer/index.ts
  packages/hooks/src/components/use-transfer/transfer-context.ts
  packages/shineout/src/transfer/__doc__/changelog.cn.md
  packages/shineout/src/transfer/__example__/04-filter.tsx
  packages/shineout/src/transfer/__example__/05-custom-filter.tsx
  packages/shineout/src/transfer/transfer.tsx
Labels: feature

#1177 chore: 更新版本号至 3.7.2，修正相关文档和代码中的版本信息
  package.json
  packages/shineout-style/src/version.ts
  packages/shineout/src/index.ts
  packages/shineout/src/upload/__doc__/changelog.cn.md
Labels: merge

#1181 fix: 更新版本号至 3.7.3-beta.3，修复 `Form` 组件在开启 `scrollToError` 后，Input组件的 `onEnterPress` 事件不触发的问题
  package.json
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1182 fix: 修复 `Input` 组件的 `onEnterPress` 事件在开启 `Form` 的`scrollToError` 后偶现无法触发的问题
  package.json
  packages/base/src/input/simple-input.tsx
  packages/hooks/src/components/use-form/use-form.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
  packages/shineout/src/input/__doc__/changelog.cn.md
Labels: bug, playground

#1186 fix: 更新版本号至 3.7.3-beta.6，修复 `Skeleton` 组件在微前端下动画效果不生效的问题
  package.json
  packages/shineout-style/src/skeleton/skeleton.ts
  packages/shineout/src/skeleton/__doc__/changelog.cn.md
Labels: bug

#1192 fix: 更新版本号至 3.7.3-beta.7，修复 `Cascader` 组件在多选模式下末级叶子节点勾选框点击失效的问题
  package.json
  packages/base/src/cascader/node.tsx
  packages/shineout/src/cascader/__doc__/changelog.cn.md
Labels: bug

#1196 feat: `setToken` 新增忽略扩展样式开关 `ignoreExtra` 用于屏蔽兼容老版本组件的额外 cssvar
  docs/markdown/shineout/changelog-common.md
  package.json
  packages/theme/src/utils/token-setter.ts
Labels: enhancement

#1193 feat: 文档的高亮目录自动跳转
  docs/theme/layout/desktop/menu/index.tsx
  docs/theme/layout/desktop/menu/menu-item.tsx
  packages/shineout/src/modal/__example__/01-base.tsx
  packages/shineout/src/modal/__test__/__snapshots__/modalSnapshot.spec.tsx.snap
Labels: documentation

#1204 fix: 修复 `Table` 的column里有列是动态fixed时, 固定列的吸附位置不正确的问题
  package.json
  packages/base/src/table/td.tsx
  packages/shineout/src/table/__doc__/changelog.cn.md
Labels: bug

#1208 fix: 优化 useFormRef 函数，使用 useState 替代 useRef 管理表单引用状态
  package.json
  packages/hooks/src/components/use-form/use-form-context.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug, playground

#1210 fix: 更新版本号至 3.7.4-beta.8，修复 `Form.Item` 嵌套使用时，子级的 `required` 属性设置为 `false` 不生效的问题，并新增样式支持
  package.json
  packages/base/src/form/form-item.tsx
  packages/base/src/form/form-item.type.ts
  packages/shineout-style/src/form/form-item.ts
  packages/shineout/src/form/__doc__/changelog.cn.md
Labels: bug

#1211 chore: 发布3.7.4
  package.json
  packages/shineout/src/input/__example__/04-02-group-seperate.tsx
Labels: merge

#1212 test: 增加 TreeSelect 组件在多选模式下的 onChangeAddition 回调测试，验证选中和取消选中的状态及参数
  packages/shineout/src/tree-select/__test__/treeSelect.spec.tsx
Labels: test-spec

#1214 feat: 添加 Select 组件 preventEnterSelect 属性
  package.json
  packages/base/src/select/select.tsx
  packages/base/src/select/select.type.ts
  packages/shineout/src/select/__doc__/changelog.cn.md
  packages/shineout/src/select/__example__/09-01-prevent-enter-select.tsx
  packages/shineout/src/select/__test__/select.spec.tsx
Labels: feature
